
SOURCE = $(wildcard *.c)
OBJS = $(patsubst %.c,%.o,$(SOURCE))
CXX = gcc
CLFAGS += -Wall 
LDFLAGS += -lm
all:bts
bts:$(OBJS)
	$(CROSS_COMPILE)$(CXX) -Wall $(CFLAGS) -o $@ $^

.PHONY:clean
clean:
	rm -f *.o *.d bts

-include $(SOURCE:.c=.d)	
		
%.o:%.c
	$(CROSS_COMPILE)$(CXX) -Wall $(CFLAGS) -c $< -o $@

%.d: %.c
	@set -e; rm -f $@; \
	$(CXX) -MM $(CFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$


